name: wsi
# CUDA version 11.6.0
channels:
  - defaults
  - nvidia
  - conda-forge

dependencies:
  - python=3.9.15
  - Pillow
  - mamba
  - conda
  - wget
  - netCDF4
  - vim
  - tensorboard
  - openssh
  - tensorflow-gpu>=2.11
  - tensorflow>=2.11
  - nvidia::cuda-nvcc
  - cuda-cudart # for JAX
  - cudatoolkit
  - esri::tensorflow-addons
  - python-javabridge
  - ray-all
#  - cyclus::java-jre
  - scipy
  - pandas
  - scikit-image
  - matplotlib
  - numpy<1.24 # for ray
#  - openslide
#  - openslide-python
  - graphviz
  - poppler
  - pyarrow # for ray
  - pip
platforms:
  - linux-64